Repository typelevel/otel4s, pull requests merged in 2024-11, with the labels that each got.

#838 prometheus exporter: add shutdown timeout config
  build.sbt
  docs/sdk/configuration.md
  sdk-exporter/prometheus/src/main/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusMetricExporter.scala
  sdk-exporter/prometheus/src/main/scala/org/typelevel/otel4s/sdk/exporter/prometheus/autoconfigure/PrometheusMetricExporterAutoConfigure.scala
  sdk-exporter/prometheus/src/test/scala/org/typelevel/otel4s/sdk/exporter/prometheus/autoconfigure/PrometheusMetricExporterAutoConfigureSuite.scala
Labels: documentation, module:sdk:exporter

#840 docs: update scala-cli directives (lib -> dep, java-opt -> javaOpt)
  docs/customization/histogram-custom-buckets/README.md
  docs/examples/grafana/README.md
  docs/examples/honeycomb/README.md
  docs/examples/jaeger-docker/README.md
  docs/index.md
  docs/instrumentation/metrics-jvm-runtime.md
  docs/instrumentation/metrics.md
  docs/instrumentation/tracing.md
  docs/sdk/aws-resource-detectors.md
  docs/sdk/aws-xray-propagator.md
  docs/sdk/aws-xray.md
  docs/sdk/overview.md
  docs/sdk/prometheus-exporter.md
Labels: documentation

#839 docs: add OtelJava section
  docs/directory.conf
  docs/instrumentation/directory.conf
  docs/instrumentation/tracing.md
  docs/oteljava/directory.conf
  docs/oteljava/metrics-jvm-runtime.md
  docs/oteljava/overview.md
  docs/oteljava/tracing-java-interop.md
  docs/sdk/overview.md
  oteljava/all/src/main/scala/org/typelevel/otel4s/oteljava/OtelJava.scala
Labels: documentation, module:oteljava

#841 docs: add SDK testkit documentation
  build.sbt
  docs/sdk/directory.conf
  docs/sdk/testkit.md
Labels: documentation

#842 docs: add OtelJava testkit documentation
  build.sbt
  docs/oteljava/directory.conf
  docs/oteljava/testkit.md
Labels: documentation

#843 docs: fix dependency in oteljava testkit example
  docs/oteljava/testkit.md
Labels: documentation

#844 docs: sort metrics by name
  docs/oteljava/testkit.md
  docs/sdk/testkit.md
Labels: documentation

#845 docs: improve overview, describe features
  README.md
  docs/index.md
Labels: documentation

#851 docs: Fix curl request example for prometheus exporter
  docs/sdk/prometheus-exporter.md
Labels: documentation

#852 Scaladoc: use `@note` tag
  core/trace/src/main/scala-2/org/typelevel/otel4s/trace/SpanMacro.scala
  core/trace/src/main/scala-3/org/typelevel/otel4s/trace/SpanMacro.scala
  core/trace/src/main/scala/org/typelevel/otel4s/trace/Span.scala
  sdk/common/shared/src/main/scala/org/typelevel/otel4s/sdk/common/InstrumentationScope.scala
Labels: tracing, module:sdk, module:core

#853 Prometheus exporter: correctly treat wildcard Accept
  sdk-exporter/prometheus/src/main/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusHttpRoutes.scala
  sdk-exporter/prometheus/src/test/scala/org/typelevel/otel4s/sdk/exporter/prometheus/PrometheusHttpRoutesSuite.scala
Labels: module:sdk:exporter
